---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	preprocess_static(preprocess_static)
	analyst(analyst)
	builder(builder)
	verifier(verifier)
	report(report)
	mark_safe(mark_safe)
	__end__([<p>__end__</p>]):::last
	__start__ --> preprocess_static;
	analyst -.-> builder;
	analyst -.-> mark_safe;
	builder -.-> mark_safe;
	builder --> verifier;
	preprocess_static --> analyst;
	verifier -.-> builder;
	verifier -.-> mark_safe;
	verifier -.-> report;
	mark_safe --> __end__;
	report --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
